name: Terraform Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-config:
    name: Check Deploy Config
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "deploy workflow is running"
